name: dont_waste
repository: https://github.com/openfoodfoundation/openfoodnetwork

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages

  build:runner:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages
    packageFilters:
      dependsOn: build_runner

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  gen:l10n:
    run: melos exec --scope="dw_app" -- flutter gen-l10n
    description: Generate localizations

  run:web:
    run: |
      cd apps/dw_app && flutter run -d chrome --dart-define=API_BASE_URL=http://localhost:3000
    description: Run web app with local API

  run:web:prod:
    run: |
      cd apps/dw_app && flutter run -d chrome --dart-define=API_BASE_URL=https://api.openfoodnetwork.org
    description: Run web app with production API

  build:web:
    run: |
      cd apps/dw_app && flutter build web --dart-define=API_BASE_URL=https://api.openfoodnetwork.org
    description: Build web app for production

  build:apk:
    run: |
      cd apps/dw_app && flutter build apk --dart-define=API_BASE_URL=https://api.openfoodnetwork.org
    description: Build Android APK

  build:ios:
    run: |
      cd apps/dw_app && flutter build ios --dart-define=API_BASE_URL=https://api.openfoodnetwork.org
    description: Build iOS app
