import 'package:dw_domain/dw_domain.dart';

/// Demo mode flag - set when user logs in as demo
bool isDemoMode = false;

/// Demo listings data with various locations around San Francisco
final List<SurplusListing> demoListings = [
  SurplusListing(
    id: 1,
    title: 'Fresh Organic Apples',
    description: 'Crisp and delicious organic apples from local farm. Perfect for snacking or baking.',
    quantityAvailable: 25,
    unit: 'kg',
    basePrice: 4.99,
    currentPrice: 2.49,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 18)),
    pickupStartAt: DateTime.now().add(const Duration(hours: 2)),
    pickupEndAt: DateTime.now().add(const Duration(hours: 8)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7749,
    longitude: -122.4194,
    distanceKm: 0.5,
    enterprise: const EnterpriseSummary(id: 1, name: 'Green Valley Farm'),
    variant: const VariantSummary(id: 1, name: 'Organic Apples', productName: 'Apples'),
    photoUrls: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'],
  ),
  SurplusListing(
    id: 2,
    title: 'Artisan Sourdough Bread',
    description: 'Freshly baked sourdough bread. Best consumed within 2 days.',
    quantityAvailable: 15,
    unit: 'loaf',
    basePrice: 6.50,
    currentPrice: 3.25,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 6)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 4)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7849,
    longitude: -122.4094,
    distanceKm: 1.2,
    enterprise: const EnterpriseSummary(id: 2, name: 'City Bakery'),
    variant: const VariantSummary(id: 2, name: 'Sourdough', productName: 'Bread'),
    photoUrls: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
  ),
  SurplusListing(
    id: 3,
    title: 'Mixed Salad Greens',
    description: 'Fresh mixed greens including arugula, spinach, and lettuce.',
    quantityAvailable: 30,
    unit: 'bag',
    basePrice: 3.99,
    currentPrice: 1.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 24)),
    pickupStartAt: DateTime.now().add(const Duration(hours: 1)),
    pickupEndAt: DateTime.now().add(const Duration(hours: 6)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7649,
    longitude: -122.4294,
    distanceKm: 0.8,
    enterprise: const EnterpriseSummary(id: 3, name: 'Fresh Farms Co'),
    variant: const VariantSummary(id: 3, name: 'Mixed Greens', productName: 'Salad'),
    photoUrls: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400'],
  ),
  SurplusListing(
    id: 4,
    title: 'Free Range Eggs',
    description: 'Farm fresh free-range eggs. Pack of 12.',
    quantityAvailable: 20,
    unit: 'dozen',
    basePrice: 7.99,
    currentPrice: 4.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(days: 5)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 10)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7899,
    longitude: -122.4044,
    distanceKm: 1.5,
    enterprise: const EnterpriseSummary(id: 4, name: 'Happy Hens Farm'),
    variant: const VariantSummary(id: 4, name: 'Free Range', productName: 'Eggs'),
    photoUrls: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400'],
  ),
  SurplusListing(
    id: 5,
    title: 'Ripe Avocados',
    description: 'Ready-to-eat Hass avocados. Perfect ripeness.',
    quantityAvailable: 40,
    unit: 'piece',
    basePrice: 2.50,
    currentPrice: 0.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 12)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 5)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7599,
    longitude: -122.4344,
    distanceKm: 2.1,
    enterprise: const EnterpriseSummary(id: 5, name: 'Tropical Imports'),
    variant: const VariantSummary(id: 5, name: 'Hass', productName: 'Avocado'),
    photoUrls: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400'],
  ),
  SurplusListing(
    id: 6,
    title: 'Organic Milk',
    description: 'Fresh organic whole milk from grass-fed cows.',
    quantityAvailable: 50,
    unit: 'gallon',
    basePrice: 6.99,
    currentPrice: 3.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    pickupStartAt: DateTime.now().add(const Duration(hours: 1)),
    pickupEndAt: DateTime.now().add(const Duration(hours: 8)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7949,
    longitude: -122.3994,
    distanceKm: 1.8,
    enterprise: const EnterpriseSummary(id: 6, name: 'Meadow Dairy'),
    variant: const VariantSummary(id: 6, name: 'Whole Milk', productName: 'Milk'),
    photoUrls: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400'],
  ),
  SurplusListing(
    id: 7,
    title: 'Fresh Strawberries',
    description: 'Sweet California strawberries. Picked this morning.',
    quantityAvailable: 35,
    unit: 'lb',
    basePrice: 5.99,
    currentPrice: 2.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 36)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 6)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7699,
    longitude: -122.4144,
    distanceKm: 0.9,
    enterprise: const EnterpriseSummary(id: 7, name: 'Berry Good Farms'),
    variant: const VariantSummary(id: 7, name: 'California', productName: 'Strawberries'),
    photoUrls: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400'],
  ),
  SurplusListing(
    id: 8,
    title: 'Croissants',
    description: 'Buttery French croissants. Baked fresh today.',
    quantityAvailable: 24,
    unit: 'piece',
    basePrice: 3.50,
    currentPrice: 1.50,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 8)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 4)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7799,
    longitude: -122.4244,
    distanceKm: 1.1,
    enterprise: const EnterpriseSummary(id: 8, name: 'French Corner Bakery'),
    variant: const VariantSummary(id: 8, name: 'Butter', productName: 'Croissant'),
    photoUrls: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400'],
  ),
  SurplusListing(
    id: 9,
    title: 'Organic Tomatoes',
    description: 'Vine-ripened organic tomatoes. Great for salads or cooking.',
    quantityAvailable: 45,
    unit: 'lb',
    basePrice: 4.49,
    currentPrice: 1.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(days: 2)),
    pickupStartAt: DateTime.now().add(const Duration(hours: 2)),
    pickupEndAt: DateTime.now().add(const Duration(hours: 10)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7549,
    longitude: -122.4394,
    distanceKm: 2.5,
    enterprise: const EnterpriseSummary(id: 9, name: 'Sunny Acres'),
    variant: const VariantSummary(id: 9, name: 'Vine Ripened', productName: 'Tomatoes'),
    photoUrls: ['https://images.unsplash.com/photo-1546470427-227c7369a9b5?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1546470427-227c7369a9b5?w=400'],
  ),
  SurplusListing(
    id: 10,
    title: 'Greek Yogurt',
    description: 'Creamy Greek yogurt. Plain, unsweetened.',
    quantityAvailable: 60,
    unit: 'cup',
    basePrice: 2.99,
    currentPrice: 1.49,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(days: 7)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 12)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7849,
    longitude: -122.3944,
    distanceKm: 1.3,
    enterprise: const EnterpriseSummary(id: 10, name: 'Olympus Dairy'),
    variant: const VariantSummary(id: 10, name: 'Plain', productName: 'Greek Yogurt'),
    photoUrls: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400'],
  ),
  SurplusListing(
    id: 11,
    title: 'Fresh Salmon Fillet',
    description: 'Wild-caught Pacific salmon. Sushi grade quality.',
    quantityAvailable: 15,
    unit: 'lb',
    basePrice: 18.99,
    currentPrice: 11.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 10)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 4)),
    status: 'active',
    visibility: 'public',
    latitude: 37.8049,
    longitude: -122.4094,
    distanceKm: 3.2,
    enterprise: const EnterpriseSummary(id: 11, name: 'Ocean Fresh Market'),
    variant: const VariantSummary(id: 11, name: 'Wild Caught', productName: 'Salmon'),
    photoUrls: ['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=400'],
  ),
  SurplusListing(
    id: 12,
    title: 'Assorted Sushi Rolls',
    description: 'Chef-prepared sushi rolls. Variety pack of 24 pieces.',
    quantityAvailable: 10,
    unit: 'box',
    basePrice: 24.99,
    currentPrice: 14.99,
    currency: 'USD',
    expiresAt: DateTime.now().add(const Duration(hours: 4)),
    pickupStartAt: DateTime.now(),
    pickupEndAt: DateTime.now().add(const Duration(hours: 2)),
    status: 'active',
    visibility: 'public',
    latitude: 37.7719,
    longitude: -122.4064,
    distanceKm: 0.7,
    enterprise: const EnterpriseSummary(id: 12, name: 'Sakura Sushi'),
    variant: const VariantSummary(id: 12, name: 'Assorted', productName: 'Sushi'),
    photoUrls: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400'],
    imageUrls: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400'],
  ),
];

/// Demo reservations
final List<Reservation> demoReservations = [
  Reservation(
    id: 101,
    listing: demoListings[0],
    quantity: 5,
    totalPrice: 12.45,
    status: ReservationStatus.confirmed,
    message: 'Will pick up around 3pm',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    expiresAt: DateTime.now().add(const Duration(hours: 4)),
  ),
  Reservation(
    id: 102,
    listing: demoListings[1],
    quantity: 3,
    totalPrice: 9.75,
    status: ReservationStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
    expiresAt: DateTime.now().add(const Duration(hours: 2)),
  ),
  Reservation(
    id: 103,
    listing: demoListings[7],
    quantity: 6,
    totalPrice: 9.00,
    status: ReservationStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    expiresAt: DateTime.now().subtract(const Duration(hours: 20)),
  ),
];

/// Demo watchlist items
final List<WatchlistItem> demoWatchlist = [
  WatchlistItem(
    id: 201,
    listing: demoListings[4],
    addedAt: DateTime.now().subtract(const Duration(hours: 5)),
  ),
  WatchlistItem(
    id: 202,
    listing: demoListings[6],
    addedAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  WatchlistItem(
    id: 203,
    listing: demoListings[10],
    addedAt: DateTime.now().subtract(const Duration(hours: 12)),
  ),
];

/// Demo taxons (categories)
final List<Taxon> demoTaxons = [
  const Taxon(id: 1, name: 'Fruits', prettyName: 'Fruits'),
  const Taxon(id: 2, name: 'Vegetables', prettyName: 'Vegetables'),
  const Taxon(id: 3, name: 'Bakery', prettyName: 'Bakery'),
  const Taxon(id: 4, name: 'Dairy', prettyName: 'Dairy'),
  const Taxon(id: 5, name: 'Meat & Seafood', prettyName: 'Meat & Seafood'),
  const Taxon(id: 6, name: 'Prepared Foods', prettyName: 'Prepared Foods'),
];
